name: Deploy dev

on:
  workflow_dispatch:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci
        working-directory: ./functions

      # - name: Copy .env.production
      #   run: cp .env.production .env
      #   working-directory: ./functions

      - name: Run tests
        run: npm run test
        working-directory: ./functions

      # - name: Lint and build
      #   run: npm run build && npm run deploy-dev
      #   working-directory: ./functions
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}